image: Visual Studio 2019
platform: x64
skip_tags: true
init:
  - ps: '$env:ACI_TAG=''ACI-''+(get-date -format "yyyyMMddHH")'
build:
  parallel: true
  verbosity: minimal
install:
  - 'set QTDIR=C:\Qt\6.5.3\msvc2019_64'
  - set PATH=%QTDIR%\bin;%PATH%
  - cmd: >-
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
build_script:
  - qmake -config release alcongrator.pro
  - nmake
after_build:
  - mkdir deploy
  - cd deploy
  - copy ..\release\alcongrator.exe alcongrator.exe
  - copy ..\lib\win-gcc\lib*.dll .
  - windeployqt alcongrator.exe
  - 7z a alcongrator-win.zip *
artifacts:
  - path: deploy/alcongrator-win.zip
    name: alcongrator-win
for:
  - branches:
      only:
        - master
    deploy:
      - provider: GitHub
        tag: $(ACI_TAG)
        auth_token:
          secure: G2VFcKQ6FM7lNKSVyevBHBwwHfvZAxSttITlXyOVYyxeEJycSI3BG+Tr6ZSpHwqX
        artifact: alcongrator-win
        force_update: true
        prerelease: true
